spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/zasmyanoDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: MyNewPass
  thymeleaf:
      cache: false
      mode: HTML
      encoding: UTF-8
      prefix: file:src/main/resources/templates/
      resources:
        static-locations: file:src/main/resources/static
        cache:
          period: 0
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail}
    password: ${password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        api:
          to: ${business-mail}

review:
  api:
    baseUrl: "http://localhost:8081"

google:
  maps:
    api-key: ${mapKey}

whether:
  api-key: ${whetherKey}

